[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"
evm_version = "cancun"
ffi = false

[fmt]
line_length = 100

[rpc_endpoints]
local = "${LOCAL_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
